workspace_root: &workspace_root /go/src/github.com/gruntwork-io/module-data-storage

defaults: &defaults
  working_directory: *workspace_root
  docker:
    - image: 087285199408.dkr.ecr.us-east-1.amazonaws.com/circle-ci-test-image-base:go1.11

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - restore_cache:
          keys:
            - dep-{{ checksum "test/Gopkg.lock" }}
      - run: cd test && dep ensure
      - save_cache:
          key: dep-{{ checksum "test/Gopkg.lock" }}
          paths:
            - /go/src/github.com/gruntwork-io/module-data-storage/test/vendor
      - persist_to_workspace:
          root: *workspace_root
          paths: test/vendor

  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: *workspace_root
      - restore_cache:
          keys:
            - dep-{{ checksum "test/Gopkg.lock" }}

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/logs
            run-go-tests --circle-ci-2 --path test | tee /tmp/logs/all.log

      - run:
          name: parse test output
          command: terratest_log_parser --testlog /tmp/logs/all.log --outputdir /tmp/logs
          when: always
      - store_artifacts:
          path: /tmp/logs
      - store_test_results:
          path: /tmp/logs

  deploy:
    <<: *defaults
    steps:
      - run: git clone "git@github.com:$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME-public.git" "/go/src/github.com/$CIRCLE_PROJECT_REPONAME-public"
      - run: git clone "git@github.com:$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME.git" /go/src/github.com/$CIRCLE_PROJECT_REPONAME-clean"
      - run: rm -rf "/go/src/github.com/$CIRCLE_PROJECT_REPONAME-public"/*
      - run: docs-generator --input-path "/go/src/github.com/$CIRCLE_PROJECT_REPONAME-clean" --output-path "/go/src/github.com/$CIRCLE_PROJECT_REPONAME-public" --github-org $CIRCLE_PROJECT_USERNAME --github-repo-name $CIRCLE_PROJECT_REPONAME
      - run: cd "/go/src/github.com/$CIRCLE_PROJECT_REPONAME-public" && git-add-commit-push --commit-all --branch-name master --message "Auto-generate docs for release $CIRCLE_TAG"

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
      - test:
          requires:
            - build
