kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.name }}-role-binding
  namespace: {{ .Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.name }}-access
subjects:
  - kind: ServiceAccount
    name:  {{ .Values.serviceAccountName }}
    namespace: {{ .Values.name }}
