apiVersion: v1
data:
  spawner_ui_config.yaml: {{- .Values.spawnerUIConfig | toYaml | indent 2 }}
kind: ConfigMap
metadata:
  annotations: {}
  labels:
    app: jupyter-web-app
    kustomize.component: jupyter-web-app
  name: jupyter-web-app-config-mgf762gt24
  namespace: kubeflow