{{ if .Values.efsPath }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Values.name }}-{{ .Values.efs.pvName }}"
  labels:
    usage: "{{ .Values.name }}-efs"
spec:
  capacity:
    storage: {{ .Values.efs.storageSize }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: "{{ .Values.efs.filesystemId }}:{{ .Values.efs.Path }}"
{{ end }}
