apiVersion: kubeflow.org/v1alpha1
kind: PodDefault
metadata:
  name: init-fsx
  namespace: {{ .Values.name }}
spec:
  desc: change permissions for data directory
  selector:
    matchLabels:
      init-fsx: "true"
  initContainers:
  - name: init-data
    image: busybox:1.36
    imagePullPolicy: IfNotPresent
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "useradd -M -s /bin/sh -N -u 1000 dl-user && chmod 2775 /data && chown dl-user:dl-user /data"
    volumeMounts:
    - name: dl-fsx-claim
      mountPath: /data
