apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: "add-secret-volume"
  namespace: {{ .Values.name }}
spec:
 desc: "add secret volume"
 selector:
   matchLabels:
     add-secret-volume: "true"
 volumeMounts:
 - name: secret-volume
   mountPath: /etc/ssh-key
 volumes:
 - name: secret-volume
   secret:
     secretName: ssh-secret-{{ .Values.name }}
     defaultMode: 256