apiVersion: "kubeflow.org/v1alpha1"
kind: PodDefault
metadata:
  name: "add-service-account"
  namespace: {{ .Values.name }}
spec:
 desc: "add service account"
 selector:
   matchLabels:
     add-service-account: "true"
 serviceAccountName: {{ .Values.serviceAccountName }}
