apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvcName }}
  namespace: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.efsStorageClassName }}
  resources:
    requests:
      storage: {{ .Values.efsStorageSize }}