apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.efsPvcName }}
  namespace: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.efsPath | ternary .Values.efsStorageClassName "" }}
  resources:
    requests:
      storage: {{ .Values.efsStorageSize }}
