apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.name }}-home"
  namespace: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.efsStorageClassName }}
  resources:
    requests:
      storage: 30Gi