# ---------------------------------------------------------------------------------------------------------------------
# MODULE PARAMETERS
# These variables are expected to be passed in by the operator when calling this terraform module.
# ---------------------------------------------------------------------------------------------------------------------

variable "alarm_sns_topic_arns" {
  description = "A list of SNS topic ARNs to notify when the ELB alarms change to ALARM, OK, or INSUFFICIENT_DATA state"
  type        = list(string)
}

variable "elb_name" {
  description = "The name of the ELB"
  type        = string
}

# ---------------------------------------------------------------------------------------------------------------------
# CLOUDWATCH ALARM DEFAULTS
# ---------------------------------------------------------------------------------------------------------------------

variable "elb_backend_connection_error_threshold" {
  description = "How many backend connection errors the ELB can see over a duration of elb_backend_connection_error_period before triggering an alarm"
  type        = number
  default     = 10
}

variable "elb_backend_connection_error_period" {
  description = "The period, in seconds, over which to count backend connection errors for the ELB"
  type        = number
  default     = 60
}

variable "elb_backend_connection_treat_missing_data" {
  description = "Sets how this alarm should handle entering the INSUFFICIENT_DATA state. Based on https://goo.gl/cxzXOV. Must be one of: 'missing', 'ignore', 'breaching' or 'notBreaching'."
  type        = string
  default     = "ignore"
}

variable "elb_backend_5xx_threshold" {
  description = "How many 5xx errors the ELB can see from backends over a duration of elb_backend_5xx_period before triggering an alarm"
  type        = number
  default     = 10
}

variable "elb_backend_5xx_period" {
  description = "The period, in seconds, over which to count 5xx errors generated by the ELB backends"
  type        = number
  default     = 60
}

variable "elb_backend_5xx_evaluation_periods" {
  description = "The number of periods over which data is compared to the specified threshold."
  type        = number
  default     = 1
}

variable "elb_backend_5xx_treat_missing_data" {
  description = "Sets how this alarm should handle entering the INSUFFICIENT_DATA state. Based on https://goo.gl/cxzXOV. Must be one of: 'missing', 'ignore', 'breaching' or 'notBreaching'."
  type        = string
  default     = "ignore"
}

variable "elb_5xx_threshold" {
  description = "How many 5xx errors the ELB itself can generate over a duration of elb_5xx_period before triggering an alarm"
  type        = number
  default     = 5
}

variable "elb_5xx_period" {
  description = "The period, in seconds, over which to count 5xx errors generated by the ELB itself"
  type        = number
  default     = 60
}

variable "elb_5xx_evaluation_periods" {
  description = "The number of periods over which data is compared to the specified threshold."
  type        = number
  default     = 1
}

variable "elb_5xx_treat_missing_data" {
  description = "Sets how this alarm should handle entering the INSUFFICIENT_DATA state. Based on https://goo.gl/cxzXOV. Must be one of: 'missing', 'ignore', 'breaching' or 'notBreaching'."
  type        = string
  default     = "ignore"
}

variable "elb_high_average_latency_threshold" {
  description = "The average backend latency, in seconds, over a period of elb_high_average_latency_period that is considered too high and should trigger an alarm"
  type        = number
  default     = 3
}

variable "elb_high_average_latency_period" {
  description = "The period, in seconds, over which to measure the average backend latency"
  type        = number
  default     = 60
}

variable "elb_high_average_latency_evaluation_periods" {
  description = "The number of periods over which data is compared to the specified threshold."
  type        = number
  default     = 5
}

variable "elb_high_average_latency_treat_missing_data" {
  description = "Sets how this alarm should handle entering the INSUFFICIENT_DATA state. Based on https://goo.gl/cxzXOV. Must be one of: 'missing', 'ignore', 'breaching' or 'notBreaching'."
  type        = string
  default     = "ignore"
}

variable "elb_high_max_latency_threshold" {
  description = "The max backend latency, in seconds, over a period of elb_high_average_latency_period that is considered too high and should trigger an alarm"
  type        = number
  default     = 5
}

variable "elb_high_max_latency_period" {
  description = "The period, in seconds, over which to measure the max backend latency"
  type        = number
  default     = 60
}

variable "elb_high_max_latency_evaluation_periods" {
  description = "The number of periods over which data is compared to the specified threshold."
  type        = number
  default     = 1
}

variable "elb_high_max_latency_treat_missing_data" {
  description = "Sets how this alarm should handle entering the INSUFFICIENT_DATA state. Based on https://goo.gl/cxzXOV. Must be one of: 'missing', 'ignore', 'breaching' or 'notBreaching'."
  type        = string
  default     = "ignore"
}

variable "elb_low_request_count_threshold" {
  description = "If the ELB sees fewer that this number of requests over a period of elb_low_request_count_period, it should trigger an alarm"
  type        = number
  default     = 1
}

variable "elb_low_request_count_period" {
  description = "The period, in seconds, over which to count requests"
  type        = number
  default     = 600
}

variable "elb_low_request_count_evaluation_periods" {
  description = "The number of periods over which data is compared to the specified threshold."
  type        = number
  default     = 1
}

variable "elb_low_request_count_treat_missing_data" {
  description = "Sets how this alarm should handle entering the INSUFFICIENT_DATA state. Based on https://goo.gl/cxzXOV. Must be one of: 'missing', 'ignore', 'breaching' or 'notBreaching'."
  type        = string
  default     = "missing"
}

variable "tags" {
  description = "A map of tags to apply to the metric alarm. The key is the tag name and the value is the tag value."
  type        = map(string)
  default     = {}
}

variable "create_resources" {
  description = "Set to false to have this module skip creating resources. This weird parameter exists solely because Terraform does not support conditional modules. Therefore, this is a hack to allow you to conditionally decide if this module should create anything or not."
  type        = bool
  default     = true
}