apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    metadata:
      labels:
        app: notebook-controller
        kustomize.component: notebook-controller
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: manager
        image: public.ecr.aws/j1r0q0g6/notebooks/notebook-controller
        command:
          - /manager
        env:
          - name: ENABLE_CULLING
            value: "true"
          - name: IDLE_TIME
            value: "4320" # In minutes (3 days)
          - name: CULLING_CHECK_PERIOD
            value: "30" # Check every 30 minutes
          - name: USE_ISTIO
            valueFrom:
              configMapKeyRef:
                name: config
                key: USE_ISTIO
          - name: ISTIO_GATEWAY
            valueFrom:
              configMapKeyRef:
                name: config
                key: ISTIO_GATEWAY
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /metrics
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
      serviceAccountName: service-account
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: notebooks-controller-culling
  namespace: istio-system
spec:
  action: ALLOW
  rules:
  - to:
    - operation:
        methods: ["GET"]
        paths: ["*/api/status"]
