apiVersion: apps/v1
kind: Deployment
metadata:
  name: kf-secrets-{{ .Values.name }}-deployment
  namespace: {{ .Values.name }}
  labels:
    app: "kf-secrets-{{ .Values.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "kf-secrets-{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "kf-secrets-{{ .Values.name }}"
    spec:
      containers:
      - image: k8s.gcr.io/e2e-test-images/busybox:1.29
        command:
        - "/bin/sleep"
        - "10000"
        name: secrets
        volumeMounts:
        - mountPath: "/mnt/rds-store"
          name: "{{ .Values.rdsSecretName }}"
          readOnly: true
        - mountPath: "/mnt/aws-store"
          name: "{{ .Values.s3SecretName }}"
          readOnly: true
        - mountPath: "/mnt/ssh-store"
          name: "{{ .Values.sshKeySecretName }}"
          readOnly: true
      serviceAccountName: {{ .Values.serviceAccountName }}
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secrets
        name: "{{ .Values.rdsSecretName }}"
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secrets
        name: "{{ .Values.s3SecretName }}"
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aws-secrets
        name: "{{ .Values.sshKeySecretName }}"