apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: aws-secrets
  namespace: kubeflow
spec:
  parameters:
    objects: "- objectName: \"rds-secret\"\n  objectType: \"secretsmanager\"\n  jmesPath:\n      - path: \"username\"\n        objectAlias: \"user\"\n      - path: \"password\"\n        objectAlias: \"pass\"\n      - path: \"host\"\n        objectAlias: \"host\"\n      - path: \"database\"\n        objectAlias: \"database\"\n      - path: \"port\"\n        objectAlias: \"port\"\n- objectName: \"s3-secret\"\n  objectType: \"secretsmanager\"\n  jmesPath:\n      - path: \"accesskey\"\n        objectAlias: \"access\"\n      - path: \"secretkey\"\n        objectAlias: \"secret\"           \n"
  provider: aws
  secretObjects:
  - data:
    - key: username
      objectName: user
    - key: password
      objectName: pass
    - key: host
      objectName: host
    - key: database
      objectName: database
    - key: port
      objectName: port
    secretName: mysql-secret
    type: Opaque
  - data:
    - key: accesskey
      objectName: access
    - key: secretkey
      objectName: secret
    secretName: mlpipeline-minio-artifact
    type: Opaque
---
apiVersion: v1
kind: Pod
metadata:
  name: kubeflow-secrets-pod
  namespace: kubeflow
spec:
  containers:
  - image: public.ecr.aws/xray/aws-xray-daemon:latest
    name: secrets
    volumeMounts:
    - mountPath: /mnt/rds-store
      name: rds-secret
      readOnly: true
    - mountPath: /mnt/aws-store
      name: s3-secret
      readOnly: true
  serviceAccountName: kubeflow-secrets-manager-sa
  volumes:
  - csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: aws-secrets
    name: rds-secret
  - csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: aws-secrets
    name: s3-secret
