apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: aws-alb-ingress-controller
    kustomize.component: aws-alb-ingress-controller
  name: alb-ingress-controller
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - configmaps
  - endpoints
  - events
  - ingresses
  - ingresses/status
  - services
  verbs:
  - create
  - get
  - list
  - update
  - watch
  - patch
- apiGroups:
  - ""
  - extensions
  resources:
  - nodes
  - pods
  - secrets
  - services
  - namespaces
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: aws-alb-ingress-controller
    kustomize.component: aws-alb-ingress-controller
  name: alb-ingress-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: alb-ingress-controller
subjects:
- kind: ServiceAccount
  name: alb-ingress-controller
---
apiVersion: v1
data:
  clusterName: us-east-2-hyperfine-demo
  iamRole: arn:aws:iam::369500102003:role/kf-admin-us-east-2-hyperfine-demo-role
kind: ConfigMap
metadata:
  labels:
    app: aws-alb-ingress-controller
    kustomize.component: aws-alb-ingress-controller
  name: aws-alb-ingress-controller-config
  namespace: kubeflow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aws-alb-ingress-controller
    kustomize.component: aws-alb-ingress-controller
  name: alb-ingress-controller
  namespace: kubeflow
spec:
  selector:
    matchLabels:
      app: aws-alb-ingress-controller
      app.kubernetes.io/name: alb-ingress-controller
      kustomize.component: aws-alb-ingress-controller
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      labels:
        app: aws-alb-ingress-controller
        app.kubernetes.io/name: alb-ingress-controller
        kustomize.component: aws-alb-ingress-controller
    spec:
      containers:
      - args:
        - --ingress-class=alb
        - --cluster-name=$(CLUSTER_NAME)
        env:
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: clusterName
              name: aws-alb-ingress-controller-config
        - name: IAM_ROLE
          valueFom:
            configMapKeyRef:
              key: iamRole
              name: aws-alb-ingress-controller-config
        image: docker.io/amazon/aws-alb-ingress-controller:v1.1.5
        imagePullPolicy: Always
        name: alb-ingress-controller
      serviceAccountName: alb-ingress-controller
