// AsciiDoc TOC settings
:toc:
:toc-placement!:
:toc-title:

// GitHub specific settings. See https://gist.github.com/dcode/0cfbf2699a1fe9b46ff04c41721dda74 for details.
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= EFS Module

image:https://img.shields.io/badge/maintained%20by-gruntwork.io-%235849a6.svg[link="https://gruntwork.io/?ref=repo_aws_data_storage"]
image:https://img.shields.io/badge/tf-%3E%3D1.1.0-blue.svg[Terraform version]

This module creates an Amazon Elastic File System (EFS) file system that provides NFSv4-compatible storage that can be used
with other AWS services, such as EC2 instances.

EFS is also supported in Kubernetes via the https://github.com/kubernetes-sigs/aws-efs-csi-driver[EFS CSI driver].
Among other features, it supports `ReadWriteMany` and `ReadOnlyMany` access modes in Kubernetes, allowing a volume to be attached
to multiple pods (even across AZs) for failover/redundancy purposes. It also supports https://github.com/kubernetes-sigs/aws-efs-csi-driver#encryption-in-transit[encryption-in-transit]
for an additional layer of security.
// tag::main-content[]

toc::[]


== Features

* Create a managed NFSv4-compliant file system
* Supports encryption-at-rest and encryption-in-transit
* Automatic failover to another availability zone



== Learn

NOTE: This repo is a part of https://gruntwork.io/infrastructure-as-code-library/[the Gruntwork Infrastructure as Code
Library], a collection of reusable, battle-tested, production ready infrastructure code. If you've never used the
Infrastructure as Code Library before, make sure to read
https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library/[How to use the Gruntwork Infrastructure as Code Library]!

=== Core concepts

* https://docs.aws.amazon.com/efs/latest/ug/index.html[EFS documentation]: Amazon's docs for EFS that
  cover core concepts such as performance modes, throughput modes, mounting file systems, etc.

== Deploy

=== Non-production deployment (quick start for learning)

If you just want to try this repo out for experimenting and learning, check out the following resources:

* link:/examples[examples folder]: The `examples` folder contains sample code optimized for learning, experimenting,
  and testing (but not production usage).

=== Production deployment

If you want to deploy this repo in production, check out the following resources:

* link:/modules/efs/variables.tf[efs module variables]: Configuration variables available for the EFS module. At minimum, you should
  configure the `allow_connections_from_cidr_blocks` and `allow_connections_from_security_groups` values to only allow access
  from your private VPC(s). You may also want to enable `storage_encrypted` to encrypt data at-rest.




== Manage

=== Day-to-day operations

* https://docs.aws.amazon.com/efs/latest/ug/mounting-fs.html[How to mount an EFS file system]
* https://docs.aws.amazon.com/efs/latest/ug/efs-backup-solutions.html[How to configure backups]




== Support

If you need help with this repo or anything else related to infrastructure or DevOps, Gruntwork offers https://gruntwork.io/support/[Commercial Support] via Slack, email, and phone/video. If you're already a Gruntwork customer, hop on Slack and ask away! If not, https://www.gruntwork.io/pricing/[subscribe now]. If you're not sure, feel free to email us at link:mailto:support@gruntwork.io[support@gruntwork.io].




== Contributions

Contributions to this repo are very welcome and appreciated! If you find a bug or want to add a new feature or even contribute an entirely new module, we are very happy to accept pull requests, provide feedback, and run your changes through our automated test suite.

Please see https://gruntwork.io/guides/foundations/how-to-use-gruntwork-infrastructure-as-code-library/#contributing-to-the-gruntwork-infrastructure-as-code-library[Contributing to the Gruntwork Infrastructure as Code Library] for instructions.




== License

Please see link:/LICENSE.txt[LICENSE.txt] for details on how the code in this repo is licensed.

// end::main-content[]
